deployer:
  driveName: /dev/nvme0n1
  bootPartition: /dev/nvme0n1p1
  osPartition: /dev/nvme0n1p2
  hostname: predator-mobile
  packages:
    - base
    - linux
    - linux-firmware
    - sudo
    - vim
    - python
    - python-pip
installer:
  driveName: /dev/nvme0n1
  username: predfalcn
  password: $y$j9T$jOPk2UThDe2fZxuc5jOnV1$CEp3s0fbtRNeVzmMJcoYF8ydCHI7Tzjw/pev//gkwOC
  hostname: predator-mobile
  bootPartition: /dev/nvme0n1p1
  services:
    - NetworkManager
    - sshd
    - firewalld
    - pcscd
    - docker
  packages:
    - arch-install-scripts
    - zsh
    - zsh-completions
    - zsh-lovers
    - zsh-history-substring-search
    - zsh-autosuggestions
    - zsh-syntax-highlighting
    - git
    - npm
    - unzip
    - docker
    - docker-compose
    - xclip
    - pipewire
    - sshfs
    - packagekit-qt5
    - opensc
    - go
    - base-devel
    - neovim
    - grub
    - efibootmgr
    - qemu-full
    - virt-manager
    - virt-viewer
    - dnsmasq
    - bridge-utils
    - libguestfs
    - vde2
    - openbsd-netcat
    - firewalld
    - firefox
    - dolphin
    - spectacle
    - konsole
    - sddm
    - plasma-wayland-protocols
