installer:
  driveName: /dev/nvme0n1
  username: admin
  hostname: cyberneticks-lab
  bootPartition: /dev/nvme0n1p1
  services:
    - name: networmanager
      service: NetworkManager
    - name: openssh
      service: sshd
    - name: firewalld
      service: firewalld
  packages:
    - arch-install-scripts
    - zsh
    - zsh-completions
    - zsh-lovers
    - zsh-history-substring-search
    - zsh-autosuggestions
    - zsh-syntax-highlighting
    - nerd-fonts
    - git
    - npm
    - unzip
    - docker
    - docker-compose
    - xclip
    - pipewire
    - sshfs
    - packagekit-qt5
    - opensc
    - pcsc-tools
    - go
    - base-devel
    - neovim
